# Generated by Django 4.2.1 on 2023-08-12 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tend", "0003_catalogo_alter_project_options"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Catalogo",
        ),
        migrations.AddField(
            model_name="project",
            name="precio",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
